package cmd

import (
	"fmt"
	"io"
	"os"

	"github.com/ryanreadbooks/prae/internal/config"
	"github.com/ryanreadbooks/prae/internal/generate"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var configFile *string

// genCmd represents the gen command
var genCmd = &cobra.Command{
	Use:   "gen",
	Short: "Generate codes",
	Long:  "Generate codes based on the config file generated by init command ",
	RunE: func(cmd *cobra.Command, args []string) error {
		// read in config file
		fileName := "prae.yml"
		if configFile != nil {
			fileName = *configFile
		}

		f, err := os.Open(fileName)
		if err != nil {
			return fmt.Errorf("open config file: %w", err)
		}
		defer f.Close()
		content, err := io.ReadAll(f)
		if err != nil {
			return fmt.Errorf("read config file: %w", err)
		}

		var cfg config.Config
		err = yaml.Unmarshal(content, &cfg)
		if err != nil {
			return fmt.Errorf("parse config file: %w", err)
		}
		if err := cfg.Check(); err != nil {
			return fmt.Errorf("config invalid: %w", err)
		}

		return generate.Handle(&cfg)
	},
}

func init() {
	rootCmd.AddCommand(genCmd)
	configFile = genCmd.Flags().StringP("file", "f", "prae.yml", "the prae config file")
}
